### PR TITLE
New settings resetting code

### PR DESCRIPTION
**Pull request by Machliah**
I tidied up all the code related to changing settings and moved a few small lines around just to make it cleaner. Added pie reset and entity distance resetting functionality thanks to some code in Ravalle's fork.

### CODE REVIEW

**Comment by Machliah** [comment]
Sorry, I had no clue what I was doing with the commits and git mistakes 💀 that's why there's some garbage commits.

**Comment by SpeedNintendo** [comment]
piechart resetting doesn't work for me kek

**Comment by Machliah** [comment]
> piechart resetting doesn't work for me kek

Why don't you make a ticket in specs discord so maybe I could get more info than this. That would be helpful.

**Comment by Machliah** [comment]
Poopy code, will keep working on stuff, all poopy code.

**Pull request closed without merging**
